// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.2

package writer;

//
// IDL:Writer:1.0
//
public class _WriterStub extends org.omg.CORBA.portable.ObjectImpl
                         implements Writer
{
    private static final String[] _ob_ids_ =
    {
        "IDL:Writer:1.0",
    };

    public String[]
    _ids()
    {
        return _ob_ids_;
    }

    final public static java.lang.Class _ob_opsClass = WriterOperations.class;

    //
    // IDL:Writer/setCard:1.0
    //
    public void
    setCard(String _ob_a0,
            short _ob_a1,
            short _ob_a2,
            short _ob_a3,
            short _ob_a4)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("setCard", true);
                    out.write_string(_ob_a0);
                    out.write_short(_ob_a1);
                    out.write_short(_ob_a2);
                    out.write_short(_ob_a3);
                    out.write_short(_ob_a4);
                    in = _invoke(out);
                    return;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("setCard", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                WriterOperations _ob_self = (WriterOperations)_ob_so.servant;
                try
                {
                    _ob_self.setCard(_ob_a0, _ob_a1, _ob_a2, _ob_a3, _ob_a4);
                    return;
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:Writer/setMessage:1.0
    //
    public void
    setMessage(String _ob_a0)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("setMessage", true);
                    out.write_string(_ob_a0);
                    in = _invoke(out);
                    return;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("setMessage", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                WriterOperations _ob_self = (WriterOperations)_ob_so.servant;
                try
                {
                    _ob_self.setMessage(_ob_a0);
                    return;
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:Writer/writeCard:1.0
    //
    public String
    writeCard(String _ob_a0)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("writeCard", true);
                    out.write_string(_ob_a0);
                    in = _invoke(out);
                    String _ob_r = in.read_string();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("writeCard", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                WriterOperations _ob_self = (WriterOperations)_ob_so.servant;
                try
                {
                    return _ob_self.writeCard(_ob_a0);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }
}
