// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.2

package writer;

//
// IDL:Writer:1.0
//
final public class WriterHolder implements org.omg.CORBA.portable.Streamable
{
    public Writer value;

    public
    WriterHolder()
    {
    }

    public
    WriterHolder(Writer initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = WriterHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        WriterHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return WriterHelper.type();
    }
}
