// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.2

package lock;

//
// IDL:Lock:1.0
//
/***/

public interface Lock extends LockOperations,
                              org.omg.CORBA.Object,
                              org.omg.CORBA.portable.IDLEntity
{
}
