// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.2

package lock;

//
// IDL:Lock:1.0
//
final public class LockHolder implements org.omg.CORBA.portable.Streamable
{
    public Lock value;

    public
    LockHolder()
    {
    }

    public
    LockHolder(Lock initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = LockHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        LockHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return LockHelper.type();
    }
}
