// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.2

package lock;

//
// IDL:Lock:1.0
//
/***/

public interface LockOperations
{
    //
    // IDL:Lock/request_token:1.0
    //
    /***/

    void
    request_token(short id,
                  int logical_time);

    //
    // IDL:Lock/acquire_token:1.0
    //
    /***/

    void
    acquire_token(int[] token);

    //
    // IDL:Lock/print_message:1.0
    //
    /***/

    void
    print_message(short id);
}
