// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.2

package database;

//
// IDL:Database:1.0
//
public class _DatabaseStub extends org.omg.CORBA.portable.ObjectImpl
                           implements Database
{
    private static final String[] _ob_ids_ =
    {
        "IDL:Database:1.0",
    };

    public String[]
    _ids()
    {
        return _ob_ids_;
    }

    final public static java.lang.Class _ob_opsClass = DatabaseOperations.class;

    //
    // IDL:Database/getCardsNumber:1.0
    //
    public short
    getCardsNumber()
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getCardsNumber", true);
                    in = _invoke(out);
                    short _ob_r = in.read_short();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getCardsNumber", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DatabaseOperations _ob_self = (DatabaseOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getCardsNumber();
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:Database/getCardName:1.0
    //
    public String
    getCardName(short _ob_a0)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getCardName", true);
                    out.write_short(_ob_a0);
                    in = _invoke(out);
                    String _ob_r = in.read_string();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getCardName", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DatabaseOperations _ob_self = (DatabaseOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getCardName(_ob_a0);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:Database/getCardFile:1.0
    //
    public String
    getCardFile(short _ob_a0)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getCardFile", true);
                    out.write_short(_ob_a0);
                    in = _invoke(out);
                    String _ob_r = in.read_string();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getCardFile", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DatabaseOperations _ob_self = (DatabaseOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getCardFile(_ob_a0);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:Database/getCardURL:1.0
    //
    public String
    getCardURL(short _ob_a0)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getCardURL", true);
                    out.write_short(_ob_a0);
                    in = _invoke(out);
                    String _ob_r = in.read_string();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getCardURL", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DatabaseOperations _ob_self = (DatabaseOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getCardURL(_ob_a0);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:Database/getCardThumb:1.0
    //
    public String
    getCardThumb(short _ob_a0)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getCardThumb", true);
                    out.write_short(_ob_a0);
                    in = _invoke(out);
                    String _ob_r = in.read_string();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getCardThumb", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DatabaseOperations _ob_self = (DatabaseOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getCardThumb(_ob_a0);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:Database/getCardArea:1.0
    //
    public boolean
    getCardArea(short _ob_a0,
                org.omg.CORBA.ShortHolder _ob_ah1,
                org.omg.CORBA.ShortHolder _ob_ah2,
                org.omg.CORBA.ShortHolder _ob_ah3,
                org.omg.CORBA.ShortHolder _ob_ah4)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getCardArea", true);
                    out.write_short(_ob_a0);
                    in = _invoke(out);
                    boolean _ob_r = in.read_boolean();
                    _ob_ah1.value = in.read_short();
                    _ob_ah2.value = in.read_short();
                    _ob_ah3.value = in.read_short();
                    _ob_ah4.value = in.read_short();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getCardArea", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DatabaseOperations _ob_self = (DatabaseOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getCardArea(_ob_a0, _ob_ah1, _ob_ah2, _ob_ah3, _ob_ah4);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }
}
