// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.2

package database;

//
// IDL:Database:1.0
//
/***/

public interface DatabaseOperations
{
    //
    // IDL:Database/getCardsNumber:1.0
    //
    /***/

    short
    getCardsNumber();

    //
    // IDL:Database/getCardName:1.0
    //
    /***/

    String
    getCardName(short cardNumber);

    //
    // IDL:Database/getCardFile:1.0
    //
    /***/

    String
    getCardFile(short cardNumber);

    //
    // IDL:Database/getCardURL:1.0
    //
    /***/

    String
    getCardURL(short cardNumber);

    //
    // IDL:Database/getCardThumb:1.0
    //
    /***/

    String
    getCardThumb(short cardNumber);

    //
    // IDL:Database/getCardArea:1.0
    //
    /***/

    boolean
    getCardArea(short cardNumber,
                org.omg.CORBA.ShortHolder x,
                org.omg.CORBA.ShortHolder y,
                org.omg.CORBA.ShortHolder width,
                org.omg.CORBA.ShortHolder height);
}
