// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.2

package database;

//
// IDL:Database:1.0
//
final public class DatabaseHolder implements org.omg.CORBA.portable.Streamable
{
    public Database value;

    public
    DatabaseHolder()
    {
    }

    public
    DatabaseHolder(Database initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = DatabaseHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        DatabaseHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return DatabaseHelper.type();
    }
}
